#!/usr/bin/env bash

mkdir build &> /dev/null
tar czf build/blog.tar.gz src
scp build/blog.tar.gz $BLOG_SFTP_ADDRESS:
ssh $BLOG_SSH_ADDRESS /bin/bash << EOF
tar xzf blog.tar.gz -C $BLOG_DIR --strip-components=1
EOF

exit $?
