#!/usr/bin/env bash

mkdir build &> /dev/null

for file in src/post/*.md; do
  pandoc -f gfm -t html $file -o ${file%.md}.html;
done

tar czf build/blog.tar.gz src

scp build/blog.tar.gz $BLOG_SFTP_ADDRESS:

ssh $BLOG_SSH_ADDRESS /bin/bash << EOF
find $BLOG_DIR -mindepth 1 -delete
tar xzf blog.tar.gz -C $BLOG_DIR --strip-components=1
EOF

exit $?
